#!/usr/bin/python

import os
import time
import datetime
from optparse import OptionParser,OptionGroup
import sys
import locale
import re
from xml.dom.minidom import parse
import xml.dom.minidom

class Config:
    def __init__(self,xmlFile):
        self._unwindSymbolFiles=[]
        self._dom = xml.dom.minidom.parse(xmlFile)
        self._doc = self._dom.documentElement;
        for qpid_element in self._doc.getElementsByTagName("qpid"):
            for file_element in qpid_element.getElementsByTagName("file"):
                unwindSymbolFile={}
                unwindSymbolFile["type"] = file_element.getAttribute("type")
                unwindSymbolFile["name"] = file_element.getAttribute("name")
                unwindSymbolFile["path"] = file_element.getAttribute("path")
                self._unwindSymbolFiles.append(unwindSymbolFile)
            for file_element in qpid_element.getElementsByTagName("unwind_file"):
                unwindSymbolFile={}
                unwindSymbolFile["type"] = "unwind"
                unwindSymbolFile["name"] = file_element.getAttribute("name")
                unwindSymbolFile["path"] = file_element.getAttribute("path")
                self._unwindSymbolFiles.append(unwindSymbolFile)
config = None

def main(argv=None):
    global config
    config = Config("qpidd_stap.xml");
    cmd = "stap ";
    for unwindFile in config._unwindSymbolFiles:
        cmd += " -d " + unwindFile["path"];
    cmd += " -I tapset/";
    cmd += " -DMAXACTION=102400";
    args = len(argv)
    for i in range(1,args-1):
        cmd += " " + argv[i]
    if (args > 1):
        cmd += " " + argv[args-1]
    print("will run:'%s'\n"%cmd)
    os.system(cmd)


if "__main__" == __name__:
    main(sys.argv)
